In [1]:
import torch
import torch.nn as nn

In [9]:
input_size = 5 #입력의 크기
hidden_size = 8 #은닉 상태의 크기
inputs = torch.Tensor(1,10,5)

In [22]:
cell = nn.RNN(input_size,hidden_size,batch_first=True)#batch_first = 입력 텐서의 첫번째 차원이 배치 크기임을 알려줌
outputs,_status = cell(inputs)
print(outputs)#10번의 시점동안 8차원의 은닉상태가 출력
print(outputs.shape)
print(_status)#마지막 시점의 은닉상태 출력
print(_status.shape)

tensor([[[-0.0791, -0.4883,  0.2994, -0.4270,  0.3665,  0.1137, -0.0412,
           0.1048],
         [-0.2955, -0.6535,  0.2947, -0.5609,  0.4395,  0.3463,  0.0953,
           0.0038],
         [-0.2995, -0.7340,  0.2457, -0.5162,  0.5455,  0.3584,  0.1615,
          -0.1095],
         [-0.2730, -0.7356,  0.2241, -0.4734,  0.5984,  0.3536,  0.1844,
          -0.1170],
         [-0.2572, -0.7324,  0.2211, -0.4551,  0.6133,  0.3452,  0.1917,
          -0.0880],
         [-0.2554, -0.7303,  0.2298, -0.4550,  0.6116,  0.3459,  0.1923,
          -0.0693],
         [-0.2589, -0.7316,  0.2331, -0.4591,  0.6082,  0.3483,  0.1930,
          -0.0659],
         [-0.2607, -0.7327,  0.2337, -0.4607,  0.6073,  0.3495,  0.1934,
          -0.0688],
         [-0.2609, -0.7331,  0.2329, -0.4605,  0.6078,  0.3496,  0.1937,
          -0.0709],
         [-0.2605, -0.7331,  0.2325, -0.4599,  0.6083,  0.3493,  0.1938,
          -0.0713]]], grad_fn=<TransposeBackward1>)
torch.Size([1, 10, 8])
tensor([[[-0.26

#깊은 순환 신경망
##깊은 순환 신경망의 장점은 머지?
##왜 _ouputs의 layer는 왜 증가하지 않았지?

In [25]:
cell = nn.RNN(input_size,hidden_size,num_layers=2,batch_first=True)
outputs,_status = cell(inputs)
print(outputs)
print(outputs.shape)
print(_status)
print(_status.shape)
#_status의 층이 2개로 늘어난 것을 확인 할 수 있음

tensor([[[ 0.2400, -0.0525,  0.2470,  0.3511, -0.2174, -0.1766, -0.2904,
           0.3510],
         [ 0.1748,  0.0693,  0.1633,  0.3053, -0.3476, -0.1422, -0.3779,
           0.1406],
         [ 0.1092,  0.0402,  0.1918,  0.3710, -0.4009, -0.1424, -0.3462,
           0.1306],
         [ 0.0489,  0.0551,  0.2208,  0.3644, -0.3895, -0.1533, -0.3521,
           0.1282],
         [ 0.0380,  0.0341,  0.2306,  0.3739, -0.3849, -0.1771, -0.3572,
           0.1580],
         [ 0.0372,  0.0382,  0.2272,  0.3816, -0.3777, -0.1742, -0.3480,
           0.1531],
         [ 0.0404,  0.0391,  0.2257,  0.3784, -0.3709, -0.1700, -0.3515,
           0.1563],
         [ 0.0450,  0.0358,  0.2244,  0.3777, -0.3709, -0.1694, -0.3485,
           0.1570],
         [ 0.0457,  0.0368,  0.2234,  0.3767, -0.3705, -0.1681, -0.3482,
           0.1542],
         [ 0.0457,  0.0367,  0.2235,  0.3762, -0.3709, -0.1676, -0.3488,
           0.1549]]], grad_fn=<TransposeBackward1>)
torch.Size([1, 10, 8])
tensor([[[-0.18

#양방향 순환 신경망

In [29]:
cell = nn.RNN(input_size,hidden_size,num_layers=2,batch_first=True,bidirectional=True)
ouputs,_status=cell(inputs)
print(ouputs.shape)
print(_status.shape)
#ouputs의 은닉 상태의 크기가 2배 즉 이전,이후의 은닉 상태가 더 해졌기 때문
#_status는 층의 개수가 두 배인데 이 역시 정방향 역방향 이기 때문

torch.Size([1, 10, 16])
torch.Size([4, 1, 8])
