#X와 y분리하기

#zip 함수를 이용한 분리

In [1]:
X,y = zip(['a',1],['b',2],['c',3])
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


In [3]:
sequences=[['a',1],['b',2],['c',3]]
X,y = zip(*sequences)#*함수의 파라미터 개수 제한 없애줌
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


#DataFrame을 이용한 데이터 분리

In [7]:
import pandas as pd

values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']#열 이름 지정
df = pd.DataFrame(values,columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [10]:
x=df['메일 본문']
y=df['스팸 메일 유무']
print(x,y)

0          당신에게 드리는 마지막 혜택!
1      내일 뵐 수 있을지 확인 부탁드...
2      도연씨. 잘 지내시죠? 오랜만입...
3    (광고) AI로 주가를 예측할 수 있다!
Name: 메일 본문, dtype: object 0    1
1    0
2    0
3    1
Name: 스팸 메일 유무, dtype: int64


#numpy를 이용하여 분리하기

In [12]:
import numpy as np
ar = np.arange(0,16).reshape((4,4))
print(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [17]:
X=ar[:,:3]
print(X)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [18]:
y=ar[:,3]
print(y)

[ 3  7 11 15]


#테스트 데이터 분리하기

#사이킷 런을 이용한 분리

In [24]:
from sklearn.model_selection import train_test_split
X,y=np.arange(10).reshape((5,2)),range(5)

print(X)
print(list(y))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


In [27]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=1234)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[2 3]
 [4 5]
 [6 7]]
[[8 9]
 [0 1]]
[1, 2, 3]
[4, 0]


#수동으로 분리하기

In [29]:
import numpy as np
X,y=np.arange(0,24).reshape((-1,2)),range(12)
print(X)
print(y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
range(0, 12)


In [32]:
n_of_train=int(len(X)*0.8)
n_of_test=int(len(X)-n_of_train)

9 3


In [35]:
X_test = X[n_of_train:]
y_test = y[n_of_train:]
X_train = X[:n_of_train]
y_train = y[:n_of_train]
print(X_test,X_train)

[[18 19]
 [20 21]
 [22 23]] [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]
