In [ ]:
#numpy를 이용한 실습

In [4]:
import numpy as np

#1차원 벡터

In [9]:
t=np.array([0.,1.,2.,3.,5.,6.])
print(t)
list_=list(range(0,6))
a=np.array(list_)
print(a)

[0. 1. 2. 3. 5. 6.]
[0 1 2 3 4 5]


In [13]:
print(t.ndim)#차원
print(t.shape)#크기
t[2:5]#slicing

1
(6,)


array([2., 3., 5.])

In [14]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [15]:
print(t.ndim)#차원
print(t.shape)#크기
t[2:5]#slicing

2
(4, 3)


array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

#토치를 이용한 실습

In [16]:
import torch

In [51]:
t=torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)
t=torch.FloatTensor([[3],[4]])
print(t)
print(t.size())

tensor([0., 1., 2., 3., 4., 5., 6.])
tensor([[3.],
        [4.]])
torch.Size([2, 1])


In [32]:
print(t.dim())
print(t.size())
print(t.shape)
print(t[2:5])

1
torch.Size([7])
torch.Size([7])
tensor([2., 3., 4.])


In [35]:
t = torch.FloatTensor([[1., 2., 3.],
                       [1., 2., 3.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [42]:
print(t.dim())
print(t.size())
print(t.shape)
print(t[2:5])
print(t[:,1])
print(t[1,:])
print(t[:,:-1])

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([ 2.,  2.,  8., 11.])
tensor([1., 2., 3.])
tensor([[ 1.,  2.],
        [ 1.,  2.],
        [ 7.,  8.],
        [10., 11.]])


#브로드캐스팅-연산이 안되는 행렬들을 torch자체 적으로 행렬을 변환시켜 연산하는것

In [53]:
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([2,2])
print(m1+m2)
#원래 연산 가능 1*2의 두 개의 행렬이라

m_1 = torch.FloatTensor([1,2])
m_2 = torch.FloatTensor([3])
print(m_1 + m_2)
#원래는 1*2 1*1로 연산이 불가능해야하지만 브로드캐스팅을 통해 연산을 함
m_3 = torch.FloatTensor([1,2])
m_4 = torch.FloatTensor([[3],[4]])
print(m_4+m_3)
#각 행렬을 2*2 행렬로 연장(브로드캐스팅)해서 연산이 진행됨
#에러가 나지 않으므로 분석자는 주의해서 실행해야함

tensor([5., 5.])
tensor([4., 5.])
tensor([[4., 5.],
        [5., 6.]])


#자주 사용되는 기능들

In [69]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1.matmul(m2))
#행렬의 곱

print(m1.mul(m2))
#원소끼리의 곱(브로드캐스팅해서 연산함)

print(m1.mean())
print(m1.mean(dim=0))#행을 제거하겠다는 의미
#평균을 의미 dim=0 행을 의미,dim=1 열을 의미

print(m1.sum())
print(m1.sum(dim=0))#행을 제거
print(m1.sum(dim=1))#열을 제거
#행렬의 합

print(m1.max())
print(m1.max(dim=0))#argmax도 같이 반환
#argmax = 최대값의 인덱스(제거된 행렬에서의 인덱스를 말함)
print(m1.max(dim=0)[0])#인덱스를 통해 max값만 혹은 argmax값만 받을 수도 있음


tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor(2.5000)
tensor([2., 3.])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
tensor([3., 4.])


In [79]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)
ft_changed = ft.view([-1,3])#-1은 torch에게 맡긴다는 뜻 즉 행의 수는 마음대로 하되 열은 3으로 하라는 뜻
print(ft_changed)
#view는 행렬의 shape를 바꿔줌
ft_chan = ft.view([-1,1,3])
print(ft_chan)

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])


In [86]:
ft=torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)
ft_sqe = ft.squeeze()
print(ft_sqe)
print(ft_sqe.shape)
#squeeze는 차원이 1인 경우 해당차원을 제거함

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


In [90]:
ft = torch.Tensor([0, 1, 2])
print(ft)
print(ft.shape)
print(ft.unsqueeze(1))
print(ft.unsqueeze(0).shape)
#unsqeeze(dim)dim=0이면 행에 크기가 1인 차원을 1이면 열에 크기가 1인 차원을 추가해줌

tensor([0., 1., 2.])
torch.Size([3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([1, 3])


In [94]:
print(ft)
print(ft.long())
#casting을 통한 원소의 type을 변형시킬 수 있음
bt = torch.ByteTensor([True, False, False, True])#바이트 단위의 텐서
print(bt)
print(bt.float(),bt.long())

tensor([0., 1., 2.])
tensor([0, 1, 2])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1., 0., 0., 1.]) tensor([1, 0, 0, 1])


In [99]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
xy_0 = torch.cat([x,y],dim=0)#0=행으로 합치기 1=열로 합치기
xy_1 = torch.cat([x,y],dim=1)
print(xy_0,xy_1)
#cat을 통한 텐서 합치기

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [103]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(torch.stack([x, y, z]))
print(torch.stack(([x, y, z]),dim=1))
#stack을 이용한 텐서 합치기

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [107]:
x=torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)
print(torch.ones_like(x))#x 행렬을 모두 1로 채우기
print(torch.zeros_like(x))#x 행렬을 모두 0으로 채우기

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[2., 4.],
        [6., 8.]])


In [110]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2))
print(x)
print(x.mul_(2))
print(x)
#_를 붙이면 x값에 그 연산된 결과값

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
